### ISSUE TITLE
Use custom (onLongPress event )  for ContextMenu

### ISSUE THREAD

**Issue by Rachidelmahmoudi** [mpiannucci/react-native-context-menu-view#9]
Hi.
Is there any possibily to make the event that trigger ContextMenu's display custom.
because it fires only onpress event.
Thank you.

**Comment by mpiannucci** [comment]
Sorry I dont understand what you mean. Can you elaborate?

**Comment by Rachidelmahmoudi** [comment]
Yes @mpiannucci 
The ContextMenu compenent is showing on pressing the content, Can we customize this event to something like onLongPress.
Best regards.

**Comment by alessandrod** [comment]
Pretty sure @Rachidelmahmoudi is referring to https://github.com/mpiannucci/react-native-context-menu-view/pull/10

**Comment by mpiannucci** [comment]
Thanks for fixing that on android @alessandrod . @Rachidelmahmoudi is that what you referring to?

**Comment by Rachidelmahmoudi** [comment]
@alessandrod thanks for your suggestion but I want to resolve the issue from javascript side to be general over ios and Android.
Is there any solution ?
Thanks.

**Comment by mpiannucci** [comment]
So this is pretty centered around the native iOS functionality, whihc is why it only works on longpress for iOS... That is the native behavior of a context menu on iOS because this plug in uses all native views. 

On Android you can probably customize it, but I dont want to add a lot of code and long press makes it match the iOS version.

**Comment by Rachidelmahmoudi** [comment]
@mpiannucci thank you for your points.
Best regards.
